### ISSUE TITLE
train problem when using the S3dis

### ISSUE THREAD

**Issue by Jaiy** [corochann/chainer-pointnet#1]
Hello, thanks for your project. When I use "python train.py -g 0 --trans=false --method=point_cls --out=results/point_vanilla" I fail to train it, and the error can be list as below:
![2](https://user-images.githubusercontent.com/23280661/42997303-caa59194-8c48-11e8-8947-3eafc007e0aa.png)
Could you please give me some ideas to handle it ?Thanks a lot.

**Comment by corochann** [comment]
Hi, thanks for your interest and feedback.
Seems the error is happening on `chainer-chemistry` library, could you try updating the library by either way of below? (seems the `chembl_tasks` should exist in current repository https://github.com/pfnet-research/chainer-chemistry/tree/master/chainer_chemistry/datasets/molnet )
Please try in your workspace path (`/usr/Downloads/jwu`, instead of inside `chainer-pointnet` directory.)

1. install latest release of chainer-chemistry on pypi
```
pip uninstall chainer-chemistry
pip install -U chainer-chemistry --no-cache-dir
```

2. install master branch on github
```
pip uninstall chainer-chemistry
git clone https://github.com/pfnet-research/chainer-chemistry.git
pip install -e chainer-chemistry
```

**Comment by corochann** [comment]
Or maybe you need to install rdkit library...

after setting up anaconda,
```
conda install -c rdkit rdkit==2017.09.3.0
```

**Comment by Jaiy** [comment]
@corochann Hi, I tried the methods you have mentioned, unfortunately, I failed. Could you please tell the system and the version of some software(like python, anaconda,etc)Thank you very much for your kind help!

**Comment by corochann** [comment]
Errors are still in `ImportError` inside chainer chemistry??
In that case, it is actually not so related to this chainer-pointnet itself.

Are you using conda? and did you try installing rdkit??
I can see the message
"UserWarning: A module chainer_chemistry was not imported please, probably because RDkit is not installed"
Does this message still appear in your current configuration?

**Comment by Jaiy** [comment]
@corochann Hi, thanks a lot sincerely, I have handled it by conda install the rdkit! Earlier I use the anaconda2 to conda install rdkit, but unfortunately failed. Then I receive your comments, I tried the anaconda3，then it worked! Thanks a lot for yout kind help~

**Comment by corochann** [comment]
Good to know it worked 👍
